version: 0.2

phases:
  install:
    commands:
      - echo Installing backend dependencies...
      - cd backend
      - npm install
      - cd ../frontend
      - echo "Current directory: $(pwd)"
      - ls -al
      - npm install
  build:
    commands:
      - echo Building the frontend...
      - cd frontend
      - npm run build
      - cd ..
      - echo Building Docker image...
      - docker build -t ecs-blog-docker .
  post_build:
    commands:
      - echo Build complete.
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 851725307442.dkr.ecr.ap-south-1.amazonaws.com)
      - echo Tagging Docker image...
      - docker tag ecs-blog-docker:latest 851725307442.dkr.ecr.ap-south-1.amazonaws.com/ecs-blog-docker:latest
      - echo Pushing Docker image to ECR...
      - docker push 851725307442.dkr.ecr.ap-south-1.amazonaws.com/ecs-blog-docker:latest

artifacts:
  files:
    - '**/*'
  discard-paths: yes
